server {
    listen 8080;
    server_name _;
    gzip on;

    client_max_body_size 100M;

    location / {
        proxy_pass http://127.0.0.1:8888;
        proxy_read_timeout 300;  # Extend timeout for requests to port 8888
    }

    location /yourpath/ {
        proxy_pass http://127.0.0.1:5555;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 300;  # Extend timeout for requests to port 5555
    }
}
